name: Manual Build and Release

on:
  push:

jobs:
  release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Verify dist folder
        run: |
          if [ ! -d "./dist" ]; then
            echo "dist folder does not exist!";
            exit 1;
          fi

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping release."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Git tag and push
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Create release artifact
        run: |
          tar -czf dist.tar.gz dist \
            --exclude='./storybook' \
            --exclude='*.stories.js' \
            --exclude='*.stories.tsx' \
            --exclude='./stories'

      - name: Upload release asset
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          name: "v${{ steps.get_version.outputs.version }}"
          files: dist.tar.gz
          generate_release_notes: true
          make_latest: false
          draft: true
